include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude: [build/**]
  strong-mode:
   # implicit-casts: true
  #  implicit-dynamic: false
  errors:
    invalid_assignment: error
    missing_return: warning
    dead_code: info

linter:
  rules:
    - camel_case_types
